branches:
  only:
  - master
language: python
python:
- '3.6'
install:
- pip3 install -r requirements.txt
script:
- pytest test/test_daouser.py
deploy:
  provider: heroku
  api_key:
    secure: U8A3068ZsgSpqOjpmrIbWRW6HtQ/28Zy2zebCM9XnHQwOTc+jvwR+c1MeaQpVlgBSQ54CUvAM0M7jbsoU4zJiSlRwpaHo3CQ7qaoHBtRkGG75BX55hmPS20EavvkqF5bG4HEn+Gt91a38IisNLTGoMQm9bndjdrK04L1GOM+JYMclbuz1uGqwAaGboy+FkFPSc6Kt5KcH1XcS0CeRe0GXdMKfU1MRrtr95v5e+GKrvhXC7Ypz2mkPlQ3ZL0aEg49h5F9J7nGI5Iv6zOFOP6DRYw/oAYUpoDGTzEOOwpQvp6XzgRmx/bHJRGNayFNIOiGqNprjRSGxNnEwe6K8SdtFW7qWhFmU4j/Rjfkn+9CJVxwZfAA6mKtkEvmX9E+hFzuen4JoSeHR2pcHhLPmT3MEe9wss6YEjKuRHRH73Nw3b0yp8T394KefhMQgG9mm5jA1AdsUOZ1FjnjQdfCvpVWVFzls+Gg9AVmaT50B73L7EikyrZD6zuZeFWOQxwEq1zdwYFC7e7uFKdyqnKAMIA8r+KuFpgrSEzZC0ZyI68EU9p82/ZozNoZb/4jWYpA5mrkwFLx8rAwb4m4wXqKZO3Vr5Pw9/wgEWyIrCFxNOttcgdXbZKR7BWJSKqB2wI++IcHD8f7dUUlZ9/IvtI8KZBP9aKHgzaC/5cbS3OyXNLJBno=
  app: apolo-cc
