
Vagrant.configure('2') do |config|

  config.vm.box = 'azure'

  config.ssh.private_key_path = '~/SSH_APOLO/key'

  config.vm.provider :azure do |azure, override|

    azure.tenant_id       = ENV['AZURE_TENANT_ID']
    azure.client_id       = ENV['AZURE_CLIENT_ID']
    azure.client_secret   = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

  end

end
